### PR TITLE
Initial .travis.yml file and tests

### PR DESCRIPTION
**Pull request by david-martin**

### CODE REVIEW

**Comment by david-martin** [comment]
@jasonmadigan I have similar changes across all nodejs templates (at least those in template-config) to:
* add a .travis.yml
* add scripts entry for `npm test` to do a `grunt unit`
* add jshint task as a dependency of the unit & accept tasks
* switch to mocha
* add unit tests for application.js (makes sure its using fh-mbas-api correctly and mounts routes like /sys & /mbaas)
* remove `grunt.option('force', true);` so travis fails when test fail (why was this even in here???)

I have already enabled all nodejs templates in travis ci (those that weren't already enabled).
Depending on how this review goes, I think it'd be good to make these things a prerequisite for new templates.
After this review, I'll roll out the changes to all templates and create PRs.

**Comment by david-martin** [comment]
for reference only, commands run to make these changes https://gist.github.com/david-martin/233b56c3c737a74deaa9

**Comment by jasonmadigan** [comment]
:+1: @david-martin lets get this everywhere

**Comment by luigizuccarelli** [comment]
@david-martin reviewed

**Comment by jasonmadigan** [comment]
re-reviewed, waiting for squash before merging

**Pull request merged**
